//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dosyadagitimportalison.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosyalar
    {
        public int DosyaId { get; set; }
        public string DosyaBaslik { get; set; }
        public string DosyaIcerik { get; set; }
        public System.DateTime DosyaTarih { get; set; }
    
        public virtual Uye Uye { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public int KategoriId { get; internal set; }
        public int UyeId { get; internal set; }
    }
}
